pull_request_rules:
  - name: Automatic merge
    conditions:
        - author=damien-devpy
    actions:
      merge:
        method: merge

  - name: delete branch after merge
    conditions:
        - merged
    actions:
      delete_head_branch:
