# Generated by Django 4.0.2 on 2022-02-13 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokedexCreature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('total', models.IntegerField()),
                ('health_point', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('sp_atk', models.IntegerField()),
                ('sp_def', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('generation', models.IntegerField()),
                ('legendary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_type', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddConstraint(
            model_name='pokemontype',
            constraint=models.UniqueConstraint(fields=('pokemon_type',), name='unique_pokemon_type'),
        ),
        migrations.AddField(
            model_name='pokedexcreature',
            name='primary_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_type', to='pokedex.pokemontype'),
        ),
        migrations.AddField(
            model_name='pokedexcreature',
            name='secoundary_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='secoundary_type', to='pokedex.pokemontype'),
        ),
        migrations.AddConstraint(
            model_name='pokedexcreature',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_pokemon'),
        ),
    ]
