# Generated by Django 4.0.2 on 2022-02-14 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokedex", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokedexcreature",
            name="secoundary_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="secoundary_type",
                to="pokedex.pokemontype",
            ),
        ),
    ]
