# Generated by Django 4.0.2 on 2022-02-14 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokedex", "0003_rename_primary_type_pokedexcreature__primary_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pokedexcreature",
            options={"ordering": ["pokemon_id"]},
        ),
    ]
