# Generated by Django 4.0.2 on 2022-02-14 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokedex", "0003_rename_primary_type_pokedexcreature__primary_type_and_more"),
        ("pokemon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=128)),
                ("level", models.IntegerField(default=0)),
                ("experience", models.IntegerField(default=0)),
                (
                    "pokedex_creature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pokedex.pokedexcreature",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pokemon.trainer",
                    ),
                ),
            ],
        ),
    ]
